name: LuxiRPG
main: Luxiel.Main
version: 2.0
depend: [ProtocolLib,PlaceholderAPI,WorldGuard,DungeonsXL]
commands:
  rpg:
  chonclass:
    description: Doi class
  profile:
    description: Xem profile
  guild:
  g:
  xxp:
  todoi:
  td:
  thien:
  redit:
  ruttien:
  noptien:
  leveltop: